---
- ansible.builtin.name: Create tautulli system group
  ansible.builtin.group:
    name: tautulli
    system: yes
  tags:
    - tautulli

- ansible.builtin.name: Create tautulli user
  ansible.builtin.user:
    name: tautulli
    group: tautulli
    system: yes
    shell: /sbin/nologin
    create_home: false
  tags:
    - tautulli
